### ISSUE TITLE
Example for using together with GraphQL relay / pagination

### ISSUE THREAD

**Issue by tonyxiao** [acarl005/join-monster-graphql-tools-adapter#1]
Can you provide an example of how to use this repo together with pagination / relay examples shown on the official join-monster docs?

http://join-monster.readthedocs.io/en/latest/relay/
http://join-monster.readthedocs.io/en/latest/pagination/

For example, how do I do something like this in apollo server / graphql-tools world?
`const { connectionType: PostConnection } = connectionDefinitions({ nodeType: Post })`

**Comment by acarl005** [comment]
Here is an example of setting up a `Connection` on a `Ship` node in the schema language:

[https://facebook.github.io/relay/docs/graphql-relay-specification.html](https://facebook.github.io/relay/docs/graphql-relay-specification.html)

Here is the [official standard](https://facebook.github.io/relay/graphql/connections.htm), it has all the info you need to implement it in the schema language yourself.

I don't think this belongs in Join Monster's official docs. I want to keep the examples in the reference implementation. If the user wants to define the schema another way, such as with graphql-tools, they will have to port the knowledge over.

**Comment by GlennMatthys** [comment]
First link is dead, new URL: https://facebook.github.io/relay/docs/en/graphql-server-specification.html
